//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcademiaDoZe.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Idioma {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Idioma() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AcademiaDoZe.Properties.Idioma", typeof(Idioma).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aluno.
        /// </summary>
        public static string ButtonAluno {
            get {
                return ResourceManager.GetString("ButtonAluno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aulas.
        /// </summary>
        public static string ButtonAulas {
            get {
                return ResourceManager.GetString("ButtonAulas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avaliacao.
        /// </summary>
        public static string ButtonAvaliacao {
            get {
                return ResourceManager.GetString("ButtonAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colaborador.
        /// </summary>
        public static string ButtonColaborador {
            get {
                return ResourceManager.GetString("ButtonColaborador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string ButtonConfig_Content {
            get {
                return ResourceManager.GetString("ButtonConfig.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar.
        /// </summary>
        public static string buttonEditar_Content {
            get {
                return ResourceManager.GetString("buttonEditar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletar.
        /// </summary>
        public static string buttonExcluir_Content {
            get {
                return ResourceManager.GetString("buttonExcluir.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fechar.
        /// </summary>
        public static string ButtonFechar_Content {
            get {
                return ResourceManager.GetString("ButtonFechar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequência.
        /// </summary>
        public static string ButtonFrequencia {
            get {
                return ResourceManager.GetString("ButtonFrequencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Principal.
        /// </summary>
        public static string ButtonHome {
            get {
                return ResourceManager.GetString("ButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laudo Médico:.
        /// </summary>
        public static string ButtonLaudoMedico_Content {
            get {
                return ResourceManager.GetString("ButtonLaudoMedico.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logon / Logoff.
        /// </summary>
        public static string ButtonLogin {
            get {
                return ResourceManager.GetString("ButtonLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro.
        /// </summary>
        public static string ButtonLogradouro {
            get {
                return ResourceManager.GetString("ButtonLogradouro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matricula.
        /// </summary>
        public static string ButtonMatricula {
            get {
                return ResourceManager.GetString("ButtonMatricula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Novo.
        /// </summary>
        public static string buttonNovo_Content {
            get {
                return ResourceManager.GetString("buttonNovo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar.
        /// </summary>
        public static string ButtonSalvar_Content {
            get {
                return ResourceManager.GetString("ButtonSalvar.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string ButtonSenha {
            get {
                return ResourceManager.GetString("ButtonSenha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Treinos.
        /// </summary>
        public static string ButtonTreinos {
            get {
                return ResourceManager.GetString("ButtonTreinos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alergias.
        /// </summary>
        public static string CheckBoxAlergias_Content {
            get {
                return ResourceManager.GetString("CheckBoxAlergias.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diabetes.
        /// </summary>
        public static string CheckBoxDiabetes_Content {
            get {
                return ResourceManager.GetString("CheckBoxDiabetes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravidez.
        /// </summary>
        public static string CheckBoxGravidez_Content {
            get {
                return ResourceManager.GetString("CheckBoxGravidez.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labirinto.
        /// </summary>
        public static string CheckBoxLabirinto_Content {
            get {
                return ResourceManager.GetString("CheckBoxLabirinto.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lesões Musculares.
        /// </summary>
        public static string CheckBoxLesoesMusculares_Content {
            get {
                return ResourceManager.GetString("CheckBoxLesoesMusculares.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nenhum.
        /// </summary>
        public static string CheckBoxNenhum_Content {
            get {
                return ResourceManager.GetString("CheckBoxNenhum.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outras.
        /// </summary>
        public static string CheckBoxOutras_Content {
            get {
                return ResourceManager.GetString("CheckBoxOutras.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pressão Alta.
        /// </summary>
        public static string CheckBoxPressaoAlta_Content {
            get {
                return ResourceManager.GetString("CheckBoxPressaoAlta.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas Cardíacos.
        /// </summary>
        public static string CheckBoxProblemasCardiacos_Content {
            get {
                return ResourceManager.GetString("CheckBoxProblemasCardiacos.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Problemas Respiratórios.
        /// </summary>
        public static string CheckBoxProblemasRespiratorios_Content {
            get {
                return ResourceManager.GetString("CheckBoxProblemasRespiratorios.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remédios Uso Continuo.
        /// </summary>
        public static string CheckBoxRemedioUsoContinuo_Content {
            get {
                return ResourceManager.GetString("CheckBoxRemedioUsoContinuo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deseja fechar?.
        /// </summary>
        public static string CloseConfirmation {
            get {
                return ResourceManager.GetString("CloseConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encerrar Aplicação.
        /// </summary>
        public static string encerrarAplicacao_Content {
            get {
                return ResourceManager.GetString("encerrarAplicacao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admissão:.
        /// </summary>
        public static string LabelAdmissao_Content {
            get {
                return ResourceManager.GetString("LabelAdmissao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Altura:.
        /// </summary>
        public static string LabelAltura_Content {
            get {
                return ResourceManager.GetString("LabelAltura.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antebraco Dir:.
        /// </summary>
        public static string LabelAntebracoDir_Content {
            get {
                return ResourceManager.GetString("LabelAntebracoDir.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antebraco Esq:.
        /// </summary>
        public static string LabelAntebracoEsq_Content {
            get {
                return ResourceManager.GetString("LabelAntebracoEsq.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bairro:.
        /// </summary>
        public static string LabelBairro_Content {
            get {
                return ResourceManager.GetString("LabelBairro.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps Dir:.
        /// </summary>
        public static string LabelBicepsDir_Content {
            get {
                return ResourceManager.GetString("LabelBicepsDir.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Biceps Esq:.
        /// </summary>
        public static string LabelBicepsEsq_Content {
            get {
                return ResourceManager.GetString("LabelBicepsEsq.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Aluno:.
        /// </summary>
        public static string LabelCadastrarAluno_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarAluno.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Avaliação:.
        /// </summary>
        public static string LabelCadastrarAvaliacao_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarAvaliacao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Colaborador:.
        /// </summary>
        public static string LabelCadastrarColaborador_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarColaborador.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Frequência:.
        /// </summary>
        public static string LabelCadastrarFrequencia_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarFrequencia.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Logradouro:.
        /// </summary>
        public static string LabelCadastrarLogradouro_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarLogradouro.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Matricula:.
        /// </summary>
        public static string LabelCadastrarMatricula_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarMatricula.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar Senha:.
        /// </summary>
        public static string LabelCadastrarSenha_Content {
            get {
                return ResourceManager.GetString("LabelCadastrarSenha.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP:.
        /// </summary>
        public static string LabelCEP_Content {
            get {
                return ResourceManager.GetString("LabelCEP.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade:.
        /// </summary>
        public static string LabelCidade_Content {
            get {
                return ResourceManager.GetString("LabelCidade.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cintura:.
        /// </summary>
        public static string LabelCintura_Content {
            get {
                return ResourceManager.GetString("LabelCintura.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento:.
        /// </summary>
        public static string LabelComplementoPessoa_Content {
            get {
                return ResourceManager.GetString("LabelComplementoPessoa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações.
        /// </summary>
        public static string LabelConfiguracoes_Content {
            get {
                return ResourceManager.GetString("LabelConfiguracoes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxa Dir:.
        /// </summary>
        public static string LabelCoxaDir_Content {
            get {
                return ResourceManager.GetString("LabelCoxaDir.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coxa Esq:.
        /// </summary>
        public static string LabelCoxaEsq_Content {
            get {
                return ResourceManager.GetString("LabelCoxaEsq.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF:.
        /// </summary>
        public static string LabelCPF_Content {
            get {
                return ResourceManager.GetString("LabelCPF.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data:.
        /// </summary>
        public static string LabelData_Content {
            get {
                return ResourceManager.GetString("LabelData.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail:.
        /// </summary>
        public static string LabelEmailPessoa_Content {
            get {
                return ResourceManager.GetString("LabelEmailPessoa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrada:.
        /// </summary>
        public static string LabelEntrada_Content {
            get {
                return ResourceManager.GetString("LabelEntrada.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID:.
        /// </summary>
        public static string LabelID_Content {
            get {
                return ResourceManager.GetString("LabelID.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID Aluno:.
        /// </summary>
        public static string LabelIdAluno_Content {
            get {
                return ResourceManager.GetString("LabelIdAluno.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idioma / Região.
        /// </summary>
        public static string LabelIdioma_Content {
            get {
                return ResourceManager.GetString("LabelIdioma.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMC:.
        /// </summary>
        public static string LabelIMC_Content {
            get {
                return ResourceManager.GetString("LabelIMC.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laudo Médico:.
        /// </summary>
        public static string LabelLaudoMedico_Content {
            get {
                return ResourceManager.GetString("LabelLaudoMedico.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LabelLogin_Content {
            get {
                return ResourceManager.GetString("LabelLogin.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logradouro:.
        /// </summary>
        public static string LabelLogradouro_Content {
            get {
                return ResourceManager.GetString("LabelLogradouro.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massa Gorda:.
        /// </summary>
        public static string LabelMassaGorda_Content {
            get {
                return ResourceManager.GetString("LabelMassaGorda.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Massa Magra:.
        /// </summary>
        public static string LabelMassaMagra_Content {
            get {
                return ResourceManager.GetString("LabelMassaMagra.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nascimento:.
        /// </summary>
        public static string LabelNascimentoPessoa_Content {
            get {
                return ResourceManager.GetString("LabelNascimentoPessoa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome:.
        /// </summary>
        public static string LabelNome_Content {
            get {
                return ResourceManager.GetString("LabelNome.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Número:.
        /// </summary>
        public static string LabelNumeroPessoa_Content {
            get {
                return ResourceManager.GetString("LabelNumeroPessoa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objetivo:.
        /// </summary>
        public static string LabelObjetivo_Content {
            get {
                return ResourceManager.GetString("LabelObjetivo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observação:.
        /// </summary>
        public static string LabelObservacaoRestricao_Content {
            get {
                return ResourceManager.GetString("LabelObservacaoRestricao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observações:.
        /// </summary>
        public static string LabelObservacoes_Content {
            get {
                return ResourceManager.GetString("LabelObservacoes.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País:.
        /// </summary>
        public static string LabelPais_Content {
            get {
                return ResourceManager.GetString("LabelPais.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panturilha Dir:.
        /// </summary>
        public static string LabelPanturilhaDir_Content {
            get {
                return ResourceManager.GetString("LabelPanturilhaDir.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Panturilha Esq:.
        /// </summary>
        public static string LabelPanturilhaEsq_Content {
            get {
                return ResourceManager.GetString("LabelPanturilhaEsq.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentual Gordura:.
        /// </summary>
        public static string LabelPercentualGordura_Content {
            get {
                return ResourceManager.GetString("LabelPercentualGordura.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso:.
        /// </summary>
        public static string LabelPeso_Content {
            get {
                return ResourceManager.GetString("LabelPeso.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Peso Ideal:.
        /// </summary>
        public static string LabelPesoIdeal_Content {
            get {
                return ResourceManager.GetString("LabelPesoIdeal.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plano:.
        /// </summary>
        public static string LabelPlano_Content {
            get {
                return ResourceManager.GetString("LabelPlano.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider:.
        /// </summary>
        public static string labelProvider_Content {
            get {
                return ResourceManager.GetString("labelProvider.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadril:.
        /// </summary>
        public static string LabelQuadril_Content {
            get {
                return ResourceManager.GetString("LabelQuadril.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-Senha:.
        /// </summary>
        public static string LabelReSenha_Content {
            get {
                return ResourceManager.GetString("LabelReSenha.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricão:.
        /// </summary>
        public static string LabelRestricao_Content {
            get {
                return ResourceManager.GetString("LabelRestricao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saída:.
        /// </summary>
        public static string LabelSaida_Content {
            get {
                return ResourceManager.GetString("LabelSaida.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha:.
        /// </summary>
        public static string LabelSenha_Content {
            get {
                return ResourceManager.GetString("LabelSenha.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha:.
        /// </summary>
        public static string LabelSenhaLogin {
            get {
                return ResourceManager.GetString("LabelSenhaLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String de Conexão:.
        /// </summary>
        public static string labelStrConexao_Content {
            get {
                return ResourceManager.GetString("labelStrConexao.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefone:.
        /// </summary>
        public static string LabelTelefonePessoa_Content {
            get {
                return ResourceManager.GetString("LabelTelefonePessoa.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo:.
        /// </summary>
        public static string labelTipo_Content {
            get {
                return ResourceManager.GetString("labelTipo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Torax:.
        /// </summary>
        public static string LabelTorax_Content {
            get {
                return ResourceManager.GetString("LabelTorax.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF:.
        /// </summary>
        public static string LabelUF_Content {
            get {
                return ResourceManager.GetString("LabelUF.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vínculo:.
        /// </summary>
        public static string labelVinculo_Content {
            get {
                return ResourceManager.GetString("labelVinculo.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrador.
        /// </summary>
        public static string RadioButtonAdministrador_Content {
            get {
                return ResourceManager.GetString("RadioButtonAdministrador.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anual.
        /// </summary>
        public static string RadioButtonAnual_Content {
            get {
                return ResourceManager.GetString("RadioButtonAnual.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Atendente.
        /// </summary>
        public static string RadioButtonAtendente_Content {
            get {
                return ResourceManager.GetString("RadioButtonAtendente.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CLT.
        /// </summary>
        public static string RadioButtonCLT_Content {
            get {
                return ResourceManager.GetString("RadioButtonCLT.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estágio.
        /// </summary>
        public static string RadioButtonEstagio_Content {
            get {
                return ResourceManager.GetString("RadioButtonEstagio.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instrutor.
        /// </summary>
        public static string RadioButtonInstrutor_Content {
            get {
                return ResourceManager.GetString("RadioButtonInstrutor.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensal.
        /// </summary>
        public static string RadioButtonMensal_Content {
            get {
                return ResourceManager.GetString("RadioButtonMensal.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semestral.
        /// </summary>
        public static string RadioButtonSemestral_Content {
            get {
                return ResourceManager.GetString("RadioButtonSemestral.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimestral.
        /// </summary>
        public static string RadioButtonTrimestral_Content {
            get {
                return ResourceManager.GetString("RadioButtonTrimestral.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salvar BD.
        /// </summary>
        public static string salvaBD_Content {
            get {
                return ResourceManager.GetString("salvaBD.Content", resourceCulture);
            }
        }
    }
}
